name: Push Container to Heroku

on:
  push:
    branches:
      - 'main'

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        # Esse comando instala o Heroku no Ubuntu do GitHub
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku Login & Container Login
        # Agora que o Heroku existe, fazemos o login
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
          heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and Push Container
        # Usando os comandos que você já conhece
        run: |
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Run Migrations
        # Aproveitando que o CLI está instalado para rodar o migrate
        run: heroku run python manage.py migrate -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}