name: Python Pull Request Workflow
on: [pull_request]
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: bookstore_dev
          POSTGRES_PASSWORD: bookstore_dev
          POSTGRES_DB: bookstore_dev_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      DEBUG: 1
      SECRET_KEY: foo
      GITHUB_ACTIONS: true
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: bookstore_dev_db
      SQL_USER: bookstore_dev
      SQL_PASSWORD: bookstore_dev
      SQL_HOST: localhost    # 👈 mudou de "db" para "localhost"
      SQL_PORT: 5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false
      
      - name: View poetry --help
        run: poetry --help
      
      - name: Install dependencies
        shell: bash
        run: python -m poetry install
      
      - name: Test
        run: |
          poetry run python manage.py test
      
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}